openapi: 3.0.0
info:
  title: Analytics
  description: A simple analytics API.
  version: 0.0.0
servers:
  - url: https://e1-analytics.herokuapp.com/1.0
  - url: http://localhost:3000/1.0
components:
  securitySchemes:
    WriteKeyHeader:
      type: apiKey
      in: header
      name: Authorization
    WriteKeyQuery:
      type: apiKey
      in: query
      name: api_key

  responses:
    BadRequestError:
      description: Missing or invalid parameters. Error messages will often contain more information to help you figure out what’s wrong.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Failed to parse data.'
              error_code:
                type: string
                default: BadRequestError
    UnauthorizedError:
      description: API key is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'The API Key is invalid.'
              error_code:
                type: string
                default: UnauthorizedError
    NotFoundError:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Resource not found.'
              error_code:
                type: string
                default: NotFoundError
    EventCreated:
      description: Event created successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              created:
                type: boolean
                default: true
  parameters:
    ProjectIdParam:
      in: path
      name: projectId
      schema:
        type: string
        example: 5e19426836270c1b1e7b03f2
      required: true
      description: ID of the project to record the event in.
    CollectionNameParam:
      in: path
      name: collectionName
      schema:
        type: string
        example: your_event
      required: true
      description: Name of the event collection to record the event in.

paths:
  /projects/{projectId}/events/{collectionName}:
    post:
      summary: Record a single event
      security:
        - WriteKeyHeader: []
        - WriteKeyQuery: []
      parameters:
        - $ref: '#/components/parameters/ProjectIdParam'
        - $ref: '#/components/parameters/CollectionNameParam'
      responses:
        '201':
          $ref: '#/components/responses/EventCreated'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      requestBody:
        description: Key value object of the event body
        required: false
        content:
          application/json:
            schema:
              type: object
              default: {}
              example: { key: 'value' }

    get:
      summary: Record a single event
      security:
        - WriteKeyHeader: []
        - WriteKeyQuery: []
      parameters:
        - $ref: '#/components/parameters/ProjectIdParam'
        - $ref: '#/components/parameters/CollectionNameParam'
        - in: query
          name: data
          schema:
            type: string
          description: URL-encoded AND base-64 encoded event body
        - in: query
          name: redirect
          schema:
            type: string
          description: A URL to redirect the request toward after the event is recorded.
      responses:
        '201':
          $ref: '#/components/responses/EventCreated'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
