name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
      - name: Install & Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          ROOT_KEY: ci-build-key
