name: Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Typedoc & Redoc
        run: |
          npm ci
          npm run docs
        env:
          CI: true
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
